### ISSUE TITLE
Search for applications broken: column "a_matched_rank" does not exist

### ISSUE THREAD

**Issue by lotharschulz** [zalando-stups/kio#91]
Kio should offer a search for application feature (`/apps?search=..`)

Use case: other services offering users to input application names can implement auto completion and similar features with search.

**Comment by hjacobs** [comment]
The search (e.g. `/apps?search=foo`) is currently broken:

```
kio-67bb9cb59c-8p96z kio ERROR [qtp1636504699-741] [GET /apps <- 178.250.115.181] i.s.s.parser - internal server error com.netflix.hystrix.exception.HystrixBadRequestException: non-fatal postgresql message
kio-67bb9cb59c-8p96z kio com.netflix.hystrix.exception.HystrixBadRequestException: non-fatal postgresql message
kio-67bb9cb59c-8p96z kio 	at org.zalando.stups.kio.sql$fn__11511$cmd_search_applications__11512.doInvoke(sql.clj:30) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at clojure.lang.RestFn.applyTo(RestFn.java:137) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at clojure.core$apply.invokeStatic(core.clj:665) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at clojure.core$apply.invoke(core.clj:660) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at com.netflix.hystrix.core$fn__9360$fn__9362.invoke(core.clj:714) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at com.netflix.hystrix.core.proxy$com.netflix.hystrix.HystrixCommand$ff19274a.run(Unknown Source) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:301) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:297) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at rx.Observable.unsafeSubscribe(Observable.java:10151) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at rx.Observable.unsafeSubscribe(Observable.java:10151) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at rx.Observable.unsafeSubscribe(Observable.java:10151) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
kio-67bb9cb59c-8p96z kio 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
kio-67bb9cb59c-8p96z kio 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_191]
kio-67bb9cb59c-8p96z kio 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_191]
kio-67bb9cb59c-8p96z kio 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
kio-67bb9cb59c-8p96z kio Caused by: org.postgresql.util.PSQLException: ERROR: column "a_matched_rank" does not exist
kio-67bb9cb59c-8p96z kio   Position: 1885
kio-67bb9cb59c-8p96z kio 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at com.jolbox.bonecp.PreparedStatementHandle.executeQuery(PreparedStatementHandle.java:174) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at clojure.java.jdbc$db_query_with_resultset$run_query_with_params__10147.invoke(jdbc.clj:890) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at clojure.java.jdbc$db_query_with_resultset.invokeStatic(jdbc.clj:904) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at clojure.java.jdbc$db_query_with_resultset.invoke(jdbc.clj:862) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:929) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at clojure.java.jdbc$query.invoke(jdbc.clj:908) ~[kio.jar:?]
kio-67bb9cb59c-8p96z kio 	at yesql.generate$query_handler.invokeStatic(generate.clj:89) ~[kio.jar:?]
^Ckio-67bb9cb59c-8p96z kio 	at yesql.generate$query_handler.invoke(generate.clj:82) ~[kio.jar:?]
```

**Comment by hjacobs** [comment]
It looks like this PR might be related: https://github.com/zalando-stups/kio/pull/103

**Comment by hjacobs** [comment]
@ethercrow can you have a look?

**Comment by hjacobs** [comment]
For reference, the internal user report via chat: "Hi Henning, writing you directly as I was not sure which team is responsible for it: The search functionality of YOUR TURN has been throwing 500 since last week, do you know who will be able to support?"
